baseURL: http://www.example.com
title: Sharif Islam
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
params:
  author: Sharif Islam, DBA, CPA, CMA
  avatarURL: images/sharif.jpg
  colorScheme: auto
  commit: https://github.com/msharifbd/SharifWebsite2
  customCSS: []
  customJS: []
  customRemoteJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Sharif Islam's personal website
  hideColorSchemeToggle: no
  info:
    - Assistant Professor
    - School of Accountancy
    - Southern Illinois University Carbondale
  keywords: Researcher, Machine Learning Enthusiast
  maxSeeAlsoItems: 5
  rtl: no
  since: 2019
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: "https://github.com/msharifbd"
      weight: 1
    - icon: fa fa-2x fa-twitter
      name: Twitter
      url: "https://twitter.com/MSharifIslam2"
      weight: 2
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: "https://www.linkedin.com/in/sharif-islam-dba-cpa-cma-09345730/"
      weight: 3
    - icon: fa fa-2x fa-facebook
      name: LinkedIn
      url: "https://www.facebook.com/in/sharif.is"
      weight: 4
      

taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: ABOUT
          url: about/
          weight: 1
        - name: BLOG
          url: posts/
          weight: 2
        - name: PROJECTS
          url: projects/
          weight: 3
        - name: BOOKS
          url: books/
          weight: 4
        - name: RESUME
          url: "CV/Sharif_Resume_R.pdf"
          weight: 5
        - name: TEACHING
          url: classes/
          weight: 6
        - name: CONTACT
          url: contact/
          weight: 7
markup:
  goldmark:
    renderer:
      unsafe: true
